name: "publish"

on: 
   push: 
     branches: [ master ]
   pull_request:
     branches: [ master ]


jobs: 
  publish:
     name: publishing
     runs-on: ubuntu-latest

     steps:
        - name: checkout 
          uses: actions/checkout@2.1.1
        - name: installation of node 
          uses: actions/setup-node@v1.4.2
          with: 
            node-version: 12
        - name: publish
          run: npm publish --access public
          env:
            token: ${{ secrets.NPM_AUTH_TOKEN }} 
        
        